# Generated by Django 6.1.1 on 2026-09-06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("licenses", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(choices=[("account", "account"), ("source", "source")], max_length=7),
                ),
                ("key_digest", models.CharField(max_length=64)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("window_started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("scope", "key_digest"), name="one_login_throttle_per_key")
                ]
            },
        )
    ]
