# Generated by Django 6.1.1 on 2026-09-06 12:22

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("licenses", "0001_initial")]

    operations = [
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("display_name__isnull", True),
                    django.db.models.lookups.LessThanOrEqual(
                        django.db.models.functions.text.Length("display_name"), 200
                    ),
                    _connector="OR",
                ),
                name="device_display_name_max_length",
            ),
        )
    ]
