# Generated by Django 6.1.1 on 2026-09-06 12:22

import django.db.models.functions.text
import django.db.models.lookups
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("licenses", "0002_loginthrottle")]

    operations = [
        migrations.CreateModel(
            name="RegistrationThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key_digest", models.CharField(max_length=64, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("window_started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("display_name__isnull", True),
                    django.db.models.lookups.LessThanOrEqual(
                        django.db.models.functions.text.Length("display_name"), 200
                    ),
                    _connector="OR",
                ),
                name="device_display_name_max_length",
            ),
        ),
    ]
